### ISSUE TITLE
Many content types do not have localization but should 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#132]
This includes: 

Blog
Front Page Box
Gallery
Slideshow
Map Records
Resource
Team 
Testimonial

It is possible that we don't need ALL of these, but we should consider this deliberately. This is on dev and distro

**Comment by PeaceGeeks** [comment]
Hey @bensinjin - this is a localization ticket from this summer. All these content types are currently missing a filter for selecting language. I am not sure how we are going about handling localization, but since we have it on some and not on others, I thought I should flag it. Your comment from Aid Watch's ticket suggests that it was only done for the content type 'Page'

**Comment by MagdiRizkallah** [comment]
Obsolete
