### ISSUE TITLE
Install Erpal

### ISSUE THREAD

**Issue by reneeblack** [PeaceGeeks/amani#396]
We would like to install and play around with Erpal as a possible PM tool for PG. Either on peacegeeks.org or projectamani.org - we aren't particularly picky. 
https://drupal.org/project/erpal

**Comment by Idevlab** [comment]
Not sure it's what you're looking for but for quick and dirty assessments of Drupal profiles and other components you can use http://simplytest.me/  I've tested Erpal using that service.

**Comment by Idevlab** [comment]
They also have demos set up for various user types at http://demo.erpal.info/

**Comment by MagdiRizkallah** [comment]
I don't think we need that now that we have SalesForce integration working.
