### ISSUE TITLE
request new password email never arrives

### ISSUE THREAD

**Issue by ronboaz** [PeaceGeeks/amani#552]
I created a new account for http://dev.rwpl.peacegeeks.org/user/login.

My account was approved. I never received an email with my password so I selected request new password, entered my email address, and saw the confirmation that an email had been sent to my email address with a new password. However that email never came. It's not in spam either. Thanks!

Ron

**Comment by nbosco** [comment]
Is this a drupal site?

**Comment by MagdiRizkallah** [comment]
Verified by Renee
