### ISSUE TITLE
Images are blurred when inserted on a Basic Page

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#571]
See http://projectamani.org/content/manage-social-media-menu

Source pics:
![571a](https://cloud.githubusercontent.com/assets/5035201/3650098/0f1122ee-1119-11e4-8059-8961ca319fbf.jpg)
![571b](https://cloud.githubusercontent.com/assets/5035201/3650100/134dd8f2-1119-11e4-87d1-9c2f409e39ad.jpg)

**Comment by PeaceGeeks** [comment]
Duplicate so closing this ticket.
