### ISSUE TITLE
Map Record Description field does not have the standard Description/Body Editing capability

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#612]
![614](https://cloud.githubusercontent.com/assets/5035201/4035663/11eb0a54-2c92-11e4-9ea4-4b216ff89ca7.JPG)

See also #595

**Comment by PeaceGeeks** [comment]
@bensinjin @mackh - can we prioritize this bug? the user experience of editing a map record description is terrible. I can't use most keyboard key strokes to edit. I have to place the cursor exactly where I want to edit. The arrow keys don't word. Its very weird. Trying to enter records for our partner in South Sudan.

**Comment by MagdiRizkallah** [comment]
please see #612 also

**Comment by ZoeAffinity** [comment]
It's a problem with the "accordion"-style fieldgroups.  If the fieldgroup type is changed to something else, eg vertical tabs, the arrow keys work normally.  See here: http://dev.amani.peacegeeks.org/node/139/edit  Is this fix good enough for production?

**Comment by MagdiRizkallah** [comment]
This is handled by #684 ...
