### ISSUE TITLE
Help to add custom block to replace social media icons on OELO for launch

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#659]

**Comment by bensinjin** [comment]
@PeaceGeeks I have added the ability to have tripadvisor icons and applied it to dev.oelo.peacegeeks.org. Add just as you would the other social media icons - ensure the menu item is labeled tripadvisor

**Comment by bensinjin** [comment]
also I have removed the custom block that was added to the context as this is no longer necessary

**Comment by MagdiRizkallah** [comment]
Verified
