### ISSUE TITLE
Can't read FB feed text in white against light great bg

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#663]
![screen shot 2015-01-06 at 10 24 58 pm](https://cloud.githubusercontent.com/assets/2263033/5641728/fdeb602e-95f2-11e4-9985-76a9bb6e5dcf.png)

**Comment by MagdiRizkallah** [comment]
Needed to change the color scheme on the block from'dark' to 'light'.  Now FB titles appear in Blue.
http://oelogabon.org/
