### ISSUE TITLE
Social media icon for Mail Chimp? 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#665]
hey @bensinjin is there a social media icon for Mail Chimp out of curiosity in the font set we currently use?

**Comment by MagdiRizkallah** [comment]
The available icons are documented here:
http://projectamani.org/content/manage-social-media-menu

**Comment by bensinjin** [comment]
what he said

**Comment by PeaceGeeks** [comment]
i mean what is the source of these? Is it font awesome?

**Comment by PeaceGeeks** [comment]
@bensinjin - can you tell me what the source is of the icons? is it font awesome?

**Comment by PeaceGeeks** [comment]
can we add icons for newsletter, an envelope perhaps?

**Comment by MagdiRizkallah** [comment]
Please take a look at the available icons above.  There is an envelope icon in the set.

The source is SS Social, a symbol font comprised of logos for popular web-based services and products: https://symbolset.com/icons/social-circle
