### ISSUE TITLE
media_bulk_upload missing

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#666]
I pulled from github last night an installed following Mack's instructions:
1) Create an empty database 
2) git clone https://github.com/PeaceGeeks/amani.git (this will create the amani directory)
3) From amani directory (in terminal): cp core/sites/default/default-settings.php core/sites/default/settings.php (copies default settings file to a new file called settings.php in core/sites/default/)
4) add your database settings to settings.php
5) navigate to <your site>/install.php (or with drush from core directory run drush si amani)
6) select amani -> procede with installation (if you see the notice) - and finish the install wizard

During the install I get this message:
Notice: Undefined index: media_bulk_upload in install_profile_modules() (line 1420 of /var/www/just/amani/amani/core/includes/install.core.inc).
Notice: Trying to get property of non-object in install_profile_modules() (line 1420 of /var/www/just/amani/amani/core/includes/install.core.inc).
Notice: Undefined index: media_bulk_upload in install_profile_modules() (line 1428 of /var/www/just/amani/amani/core/includes/install.core.inc).
Notice: Trying to get property of non-object in install_profile_modules() (line 1428 of /var/www/just/amani/amani/core/includes/install.core.inc).

When I run updates I get this message:
Unresolved dependency	media_bulk_upload (Missing)

Should I install https://www.drupal.org/project/bulk_media_upload ?

Thank you,
Andy

**Comment by andygraybeal** [comment]
Ah more googling says that it's not bulk_media_upload and I'm confused :) and that maybe it exists in the Media module.

**Comment by andygraybeal** [comment]
Now I see this: https://github.com/brantwynn/media_bulk_upload

**Comment by bensinjin** [comment]
this should be in the build already, maybe pull again.

**Comment by bensinjin** [comment]
this was a relatively new issue that surfaced when the media_gallery module was updated, it should be resolved now.

**Comment by andygraybeal** [comment]
thank you ben :)

**Comment by bensinjin** [comment]
sorry didn't notice this till now

**Comment by andygraybeal** [comment]
Yes, I just installed and this has gone away a different issue it says now -- noted in https://github.com/PeaceGeeks/amani/issues/676
