### ISSUE TITLE
Formatting Lost on the About pages

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#671]
Formatting OK on the About node view
![image](https://cloud.githubusercontent.com/assets/5035201/5711278/fdec63ce-9a5d-11e4-824a-eae11fbc1e3d.png)

But lost on the About menu view
![image](https://cloud.githubusercontent.com/assets/5035201/5711307/3491ebb0-9a5e-11e4-8abb-044747d1344c.png)

**Comment by PeaceGeeks** [comment]
@bensinjin - this doesn't seem to be fixed on distro - please fix. 

http://dev.amani.peacegeeks.org/about

**Comment by bensinjin** [comment]
it is - dev just hasn't been updated - I'll do that shortly
