### ISSUE TITLE
Sites have too many spam accounts 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#674]
Can we improve on our captcha?

**Comment by bensinjin** [comment]
these spam accounts are all registering from the same domain - drupaler.org. Seeing as our conventional spam modules don't seem to be stoping these particular bots I'm trying something new right now just on isis-wicce.org and going to see how it goes this week.

**Comment by MagdiRizkallah** [comment]
The SPAM controls have been added to the Amani Config menu.
@bensinjin please document the default settings so that I can add to the Reference manual and close this issue.

**Comment by joelpittet** [comment]
FYI two helpful modules are (spambot)[https://www.drupal.org/project/spambot] and [honeypot](https://www.drupal.org/project/honeypot) in reducing spam. If you don't already have them.

**Comment by bensinjin** [comment]
Yep, we have both

**Comment by MagdiRizkallah** [comment]
Seems to have reduced the number of SPAM accounts
