### ISSUE TITLE
User unable to edit Media 'description' upon edit

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#675]
This is the same issue we ran into back with Isoko and it now seems to be affecting distro. I was testing #668 and was trying to edit an existing media record on a 'resource' node and wanted to add a description to it, but couldn't. 

![screen shot 2015-01-13 at 12 05 38 am](https://cloud.githubusercontent.com/assets/2263033/5717602/70f02392-9ab8-11e4-95a6-fd200bf2b953.png)

**Comment by MagdiRizkallah** [comment]
This is possible by editing the media 'block' in the 'View' mode of the node.  Not intuitive, but I added a note in the documentation.
