### ISSUE TITLE
About page "cropping" strangeness.

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#678]
Strange cropping? issue on my About page.

Here is what my About page looks like: 
![about_page_cropping_issue](https://cloud.githubusercontent.com/assets/10078381/5890019/4bbf5ecc-a412-11e4-9f4c-c192548beda4.png)

Here is what it looks like in the editor:
![about_page_cropping_issue_in_editor](https://cloud.githubusercontent.com/assets/10078381/5890023/a89ce0c4-a412-11e4-81e2-972b84a548f7.png)

In the crop editor, I cannot move anything around.

**Comment by MagdiRizkallah** [comment]
It seems the pic is too small,  try a pic ~2.5 times the size of this one...  Please let me know what the minimum size is so that I can document it for next time...

**Comment by andygraybeal** [comment]
Looks like the minumum size is 800
