### ISSUE TITLE
Map filter #1 and Map filter #2, what is their intention?

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#679]
I'm wondering because I am assuming I can assign filter #1 to things like types of injustices, and filter #2 is for the sub-types of those injustices.
For example:
Type (Filter #1): Landlord Harrasment
Sub type (Filter #2): Withholding mainetance, intimidation, threats, attempt to enter apartment without cause, etc.

I wonder if that use case is a good example and if so, how do I do it?  If it isn't a good example, what is intended for these filters?

**Comment by MagdiRizkallah** [comment]
May be you can try and get the answers from the documentation for:
content types at http://projectamani.org/content/manage-content-amani-admins-editors-contributors
Amani Admin at http://projectamani.org/content/administer-content-amani-admins-only

This will help us improve it if your answers are not found there...

**Comment by andygraybeal** [comment]
Thank you for those links.  The answer is on the second link you listed here:
http://projectamani.org/content/manage-drop-down-lists

The drop down lists are for two seperate lists.  In the examples, types of injustices and their severity rating from 1-5 or whatever.  I think this is useful.

I wonder if it would be possible for Filter #1 list and each item on that list has a sub-list associated with it in Filter #2.  Instead of each item on the Filter #1 list sharing a list (the severity rating from the example).
