### ISSUE TITLE
Slideshow slide is displaying white bar on the bottom

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#682]
look at dev demo 4 for example. i have seen this on prod sites too

**Comment by MagdiRizkallah** [comment]
That must be your browser...  I have no issues with Chrome on Win 8.
![image](https://cloud.githubusercontent.com/assets/5035201/6013416/58b2d098-ab09-11e4-974f-a1481f81d94c.png)

**Comment by MagdiRizkallah** [comment]
Non issue
