### ISSUE TITLE
Fix map tiles

### ISSUE THREAD

**Issue by bensinjin** [PeaceGeeks/amani#685]
We need to user more detailed map tiles, see osm map tiles

**Comment by bensinjin** [comment]
@PeaceGeeks This has been addressed see http://dev.amani.peacegeeks.org/admin/config/incident-reports under manage amani map settings to set your default base layer, select osm fr a new detailed layer.

**Comment by PeaceGeeks** [comment]
Is this deployed to all sites now, or at least CEPO?

**Comment by MagdiRizkallah** [comment]
Thanks @bensinjin  - Could you also provide a brief explanation for each option so that I can add to the documentation...

**Comment by MagdiRizkallah** [comment]
Documentation updated without detailed explanantion
