### ISSUE TITLE
Dev site for new PeaceGeeks site

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#688]

**Comment by PeaceGeeks** [comment]
dev.pg.peacegeeks.org

**Comment by bensinjin** [comment]
@PeaceGeeks this is setup - might take a couple hours before it resolves.

**Comment by PeaceGeeks** [comment]
Great! Thanks!




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org

https://www.youtube.com/watch?v=NdwBG3Ie6eI
