### ISSUE TITLE
HTML Purifier Library location warning on install

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#690]
During installation, I get a warning about HTML Purifier being in the wrong directory.
It says:
HTML Purifier library location	
The HTML Purifier library currently lives in /var/www/peoplesjusticeleague.com/public_html/amani/modules/contrib/htmlpurifier/library, but should actually be placed in the shared libraries API at /library. You should move the folder such that /library/HTMLPurifier.auto.php exists (you will need to create an htmlpurifier folder to hold the library folder). For future updates, you can simply replace the htmlpurifier folder with the htmlpurifier-x.y.z folder that a new HTML Purifier tarball unzips to (you'll be reminded in an update notification).

**Comment by mackh** [comment]
Thanks Andy, we'll take a look at this.

**Comment by bensinjin** [comment]
@andygraybeal this can be safely ignored - it appears to be an issue with this version of the module, we're keeping an eye out for any pertinent updates to it.

**Comment by andygraybeal** [comment]
rock on thank you!
