### ISSUE TITLE
Map Record, Submitter Name (Optional) requires First & Last

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#691]
If you fill out a First name, it requires a Last name.  I wonder if it could be possible to just fill out the first name and not the last name.  A lot of the names I'm entering are false anyway to remain anonymous.

I found where to change this setting, but I'm afraid that it might have unknown problems if I change it.

**Comment by MagdiRizkallah** [comment]
May I ask why bother entering a 1st name if you would like to leave it anonymous?

**Comment by andygraybeal** [comment]
I wonder similarly as you, but some people are leaving names like "orchid" etc, they want partially anonymous, I guess, I don't know really.  I'm just mentioning it because it's a data set that I'm entering in.  I thought it would be a useful suggestion to your project.  I don't care if it is this way personally.  I'm entering Orchid for the first name and a "." for the Last name.  I changed the setting to not require Last names .. I'm not saying this caused my problems but weird things happened that time around and I started again.  I started again and I'm refraining from changing this setting this time.  Anyway, I wondered to myself if the submitters name is optional, why when you enter a first name, does it require a last name.  I'm trying to make helpful observations, that is all.  If you don't find it helpful, that is fine.

**Comment by andygraybeal** [comment]
Alright, so I now recognize the problem I was having was due to lack of memory.  Here's how to make it so that the "Family" name is not required for other people that may be interested.
Structure -> Content Types -> Map Record -> Manage Fields -> Submitter Name -> Submitter Name (Optional) Field Settings -> Minimum Components -> Deselect "Family".
Hopefully this change doesn't have any negative occurences.
