### ISSUE TITLE
After a certain amount of incident reports, there is a failure with the /incident-reports page

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#692]
On one Amani install, I have 24 incidents and the /incident-reports map fails.  I delete the 24th incident and the /incident-reports map works.

On another Amani install, it acts the same way but with 28 incidents instead of 24.

I wonder if there is some setting in my system that is causing this problem.  I'm going to try it on another machine I think.  I'm on Ubuntu 12.04.  I'm going to try 14.04.

Both installs have been cloned from github today.

**Comment by andygraybeal** [comment]
i think it is a php memory issue.  i loaded onto the other host, increased my php memory and things are going well.

**Comment by mackh** [comment]
Hi Andy

We have loaded the map with hundreds of points.  The error you are seeing could be from a memory constraint, or perhaps a browser issue.  Can you check the watchdog and apache logs for more info?  Can you also let us know what browser you are seeing and what the error looks like?  Also, if you confirm the PHP version, that would be good.  The openlayers location picker widget has a bug in 5.4+ but it sounds unrelated to this issue.

**Comment by andygraybeal** [comment]
hey, cool, thanks for the response.  i'm now pretty certain it was memory.  I'm using the latest firefox browser.

**Comment by andygraybeal** [comment]
one host is using php 5.3.10 and another is 5.5.9.
