### ISSUE TITLE
Map Filter #1 and #2 and related titles not being used on Map Record entry form

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#694]
When looking at /incident-reports Map Filter #1 and #2 faithfully reflect the titles I've given them ie "Type of Harassment" & "Bystander Intervention"

When adding a record though they still read as Map Filter #1 and #2.  I wonder if my titles could be used instead of their actual names on the /node/add/incident-report page.  It would make it easier for the random person reporting an incident to understand the form.  I wonder if there is a setting I've missed.

**Comment by bensinjin** [comment]
Thanks @andygraybeal the settings for those fields can be found at admin/config/incident-reports under the manage amani map filters part. It will now respect the Filter title values you put into these fields when creating a map record. This will be deployed to dev.amani.peacegeeks.org at some point today

**Comment by bensinjin** [comment]
this is now on dev.

**Comment by MagdiRizkallah** [comment]
Well done ... See #613

**Comment by andygraybeal** [comment]
Awesome, thank you!
