### ISSUE TITLE
Are you guys doing the automatic upgrades?

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#696]
I apologize about this entry, but I'm curious.  Drupal warns me that I need to upgrade for security purposes and when I have upgraded, things have gone wrong.  This isn't a specific request or report, this is where my apology lays, but are you guys upgrading the system and getting it to work so that Drupal's status report is positive?

**Comment by PeaceGeeks** [comment]
@mackh @bensinjin - can you comment on this? andy's instance is on his own servers.

**Comment by mackh** [comment]
We are updating the install profile.  Anyone running their own instances will need to rebuild from the profile or update their own instances of the site.

**Comment by andygraybeal** [comment]
Okay thank you.
