### ISSUE TITLE
I broke the individual incident map, not the global one.

### ISSUE THREAD

**Issue by andygraybeal** [PeaceGeeks/amani#704]
It seems I did something to break the maps for the individual incidents.  Since I noticed this, apparently new entries don't show up on the global map.

I think I might need to start over and try again.  To learn and troubleshoot I loaded up the dev branch and imported the db from the original site i had put my data into.  It works, but new entries don't show up on the map.

I'll keep working at it.  I'm sorry I don't have better information about what I did, I don't think I did anything to get it to do this.

**Comment by andygraybeal** [comment]
I need some help.

I've tried with brand new linodes instances (ubuntu 14.04), empty databases, and both master and develop branches and I cannot get the incident record to map my incidents.  
I wonder what I might be doing wrong.  

Apache v2.4.7

root@localhost:/var/log/apache2# apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 22 2014 14:36:38

PHP v5.5.9

root@localhost:/var/log/apache2# php -v
PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

MySQL v5.5.41

mysql> SHOW VARIABLES LIKE "%version%";
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.5.41                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| version                 | 5.5.41-0ubuntu0.14.04.1 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | debian-linux-gnu        |
+-------------------------+-------------------------+
7 rows in set (0.07 sec)


Here's step-by-step of what I do (please note that this is quick and dirty and not including the security stuff that i'd do with a real host, this is just for testing (ex: no SSL, disable root user, mysql security, no firewall, etc):

I use Linode.. so from the Linode Manager:
* Rebuild
* Image: Ubuntu 14.04 LTS
* Deployent Disk: 24320MB (Default)
* Swap 256MB (Default)

Boot it up.

SSH as root to it (empty my previous known_hosts key for the old host)

Run updates
 apt-get update && apt-get upgrade
 reboot

Re-login

Install LAMP
 apt-get install lamp-server^

Install PHP GD and PHP Curl libs
 apt-get install php5-gd php5-curl

Enable rewrite
  a2enmod rewrite

Edit /etc/apache2/sites-available/000-default.conf to have:
       DocumentRoot /var/www/html/core/

       <Directory /var/www/html/core/>
               AllowOverride All
       </Directory>


For whatever reason, PHP's opcache is giving me a fit during Drupal install so I disable it:
  vim /etc/php5/apache2/php.ini
   uncomment opcache.enable=0

In the past I noticed that I have problems displaying more than 15 incidents when PHP is set to 128M so, while I'm in /etc/php5/apache2/php.ini
 I change:  memory_limit = 128M 
 To be: memory_limit = 256M
  
MySQL tells me that key_buffer is deprecated and I should use key_buffer_size instead so I change it:
  vim /etc/mysql/my.conf
   from: key_buffer	=16M
   to: key_buffer_size	=16M

Restart Apache and Mysql
 service apache restart
 service mysql restart

Install git
 apt-get install git

Move so I'm in /var/www directory
 cd /var/www

Download Amani
 git clone https://github.com/PeaceGeeks/amani.git 

Move Amani to be so Apache sees it: 
 rm -rf html
 mv amani html

Give Apache ownership:
 chown -R www-data:www-data html

I'm so lazy and new to using mysql-workbench for now and so I set the mysql server to accept root from all hosts, i understand this is dangerous, but it is for testing and it is temporary.
  mysql -u root -p
  mysql> GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password';

 Edit /etc/mysql/my.cnf and comment out the bind-address line
 #bind-address 127.0.0.1

 Restart mysql

In mysql-workbench create a new schema "justice" and a new user "justice" with all privs, accept "Grant Options" to that new user on the db "justice".

In my browser, I bring up the drupal install:
 Select the Amani install profile
 English
 Fill in the DB fields
 Let it install.
 Configure the drupal site:
 and finally click to "Visit the new site". 

Once in Amani...
 I select:
  Configure Amani

 * Manage Map settings
    Configure Map
     Map Filters
      Map Filter #1 
       Filter Title - Harassment Types
      Map Filter #2
       Filter Title - Bystander Intervention
       Filter Type - Radio button
     Manage Map Record Collection - Enable for anonymous entries
   Save

 *  Manage Main Menu - Reset Default Menu links

 * Amani Admin -> Manage Drop down lists: 
    Add terms to Map Filter #1 and #2

Add incident: 
  Enter generic title, and description.
  Select the map filters
  Enter in an address and "Find address on map"
  Save

The entry has no GEOLOCATION data :( and doesn't appear on the /incident-reports page.

I'm so sad.

**Comment by andygraybeal** [comment]
Okay - I tried Ubuntu 12.04 
Apache 2.2.22
PHP 5.3.10
MySQL 5.5.41

created db and user manually w/o mysql-workbench

and everything appears to be working just fine.

**Comment by mackh** [comment]
Hey Andy

Sorry for the friction there, the OpenLayers geocoding component only wants
to work on 5.3.  We do want to figure out a better component to use there,
its just part of our legacy at the moment.   I really want to avoid having
to use 5.3, the future is now :)

-<

**Comment by andygraybeal** [comment]
Cool, thank you for the response!   I'm fine with anything, as long as I can get it to work and there isn't a huge security concern :)  Ubuntu 12.04 got til 2017, so we're good for a little while.  I'm sure your concerns are more complex.
