### ISSUE TITLE
Aid Watch site is displaying 'About' content twice, once as main and once not

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#708]
http://dev.aidwatch.peacegeeks.org/ar/about
http://dev.aidwatch.peacegeeks.org/about

It should only appear once

**Comment by PeaceGeeks** [comment]
@malcolm8 - do you have time to help out with this one?

**Comment by bensinjin** [comment]
@PeaceGeeks this has been fixed

**Comment by MagdiRizkallah** [comment]
verified
