### ISSUE TITLE
Localization issues - unable to select 'Require Language'

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#709]
Here's another issue as I tried to check the Page content type for content translation into Arabic:
http://dev.aidwatch.peacegeeks.org/admin/structure/types/manage/page 
On multilingual settings tab, under Extended language options: need to check " Require language (Do not allow Language Neutral)". However, those boxes are disabled (I do get unresponsive script: http://dev.aidwatch.peacegeeks.org/misc/ui/jquery.ui.core.min.js?v=1.8.7:17 but this is not the cause as I can set it in http://dev.aidwatch.peacegeeks.org/admin/structure/types/manage/about). Of course, we need to have the page content types in both En and Ar.
Can you please check this as well.

**Comment by bensinjin** [comment]
@PeaceGeeks Need to ensure that this setting is enabled in the publishing options section first - I've done so for the page content type.

**Comment by PeaceGeeks** [comment]
@bensinjin - see #132

**Comment by MagdiRizkallah** [comment]
verified
