### ISSUE TITLE
Page gets taken over by footer in Arabic version of About pagw

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#710]
I have noticed a recurring issue when I go to this page - http://dev.aidwatch.peacegeeks.org/ar/about

When I scroll to the bottom, the body disappears and the full page gets taken over (or seems to anyway) by the footer

![screen shot 2015-03-05 at 12 43 22 am](https://cloud.githubusercontent.com/assets/2263033/6501722/be72aa64-c2d0-11e4-9315-6e400cf694ea.png)

**Comment by bensinjin** [comment]
@PeaceGeeks I am unable to recreate this - is it still appearing this way locally?

**Comment by MagdiRizkallah** [comment]
will be resolved by theming
