### ISSUE TITLE
Upgrade the following dev sites

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#711]
dev.aidwatch.peacegeeks.org
dev.amani.peacegeeks.org
dev.cepo.peacegeeks.org
dev.coa1325.peacegeeks.org
dev.demo1.peacegeeks.org
dev.demo2.peacegeeks.org
dev.demo3.peacegeeks.org
dev.demo4.peacegeeks.org
dev.demo5.peacegeeks.org
dev.demo6.peacegeeks.org
dev.isis-wicce.peacegeeks.org
dev.nakurugbv.peacegeeks.org
dev.oelo.peacegeeks.org
dev.pg.peacegeeks.org
dev.wongosol.peacegeeks.org
dev.wpi.peacegeeks.org

**Comment by bensinjin** [comment]
@MagdiRizkallah these sites are now up to date

**Comment by MagdiRizkallah** [comment]
Tx Ben
