### ISSUE TITLE
Ticket from Aid Watch on Localization

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#714]
The page content type is not fully fixed. There should be a "Translate" tab if you edit a page (View/edit/[translate]/devel.) and this tab is still missing. You can compare the About content type for pointers.

For the Main Menu (About, News, Resources, ... Contact), there seems to be an issue with translation as well (not sure if caused by Superfish), check
http://dev.aidwatch.peacegeeks.org/ar/about  (notice the location of the Arabic text which should go uder About ( = Why Aid Watch Palestine?)
The menu item is translated at 
 http://dev.aidwatch.peacegeeks.org/admin/structure/menu/item/1001/translate (it shows Arabic as disabled in the drop down box).
I did not check the rest of the content type yet.

**Comment by MagdiRizkallah** [comment]
verified
