### ISSUE TITLE
Map map on CEPO slow to load

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#717]
map is load to load initially, then the JS is taking a while to load after the assets are there

**Comment by tnightingale** [comment]
The site has the 'Fit map to features' option checked in the [Incident Report Map configuration](http://cepo-southsudan.org/admin/config/incident-reports) (under the 'Manage Amani map settings' section).

In order for the map to know where to centre itself it needs to look at the geodata of all of the incident_report nodes in the system (currently there's 173 of them). Drupal is rather slow at loading that many nodes at once. A short-term quick-fix is to disabled the 'Fit map to features' option and manually set a lon/lat/zoom to center the map on.

**Comment by tnightingale** [comment]
I have just pushed to the develop branch updates to the custom geojson and incident_map modules.

This change updates Amani to use the latest version of the GeoJSON module we use internally at Affinity Bridge which supports caching of GeoJSON resources. Caching greatly improves loading of geodata when attempting to calculate the map center as described in the process above. 

I'm seeing the page load time of ~7-10 seconds being cut down to ~0.5 of a second on http://dev.cepo.peacegeeks.org/mapping-conflict-violence-in-south-sudan.

**Comment by MagdiRizkallah** [comment]
verified
