### ISSUE TITLE
Site features will need to right justify when switching languages (mirrored)

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#720]
Logo should be on right
Tagline to the left of the Logo
Search, Secondary Menu, Language, Social Media icons on the left
Language Separator bar moved to the Left of EN
Newsletter button on the left (and any other floating buttons)
Main menu dot on right should be moved to before the last item on the left (menu starts with a dot but there is a missing dot before the last item)
Right Region Blocks (e.g. Other Programs, Calendar, social Media feeds) should be moved to Left.

**Comment by MagdiRizkallah** [comment]
will be resolved by theming
