### ISSUE TITLE
Localization causes duplication of right Front Page Box

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#724]
Hiding the left one.  See http://dev.demo1.peacegeeks.org/ in EN & AR.  I translated only the right FPB.
Also http://dev.demo2.peacegeeks.org/ I only added one FPB

**Comment by PeaceGeeks** [comment]
This seems to be a problem in both languages, no? @MagdiRizkallah, do you only have localization on one FPB?

**Comment by MagdiRizkallah** [comment]
Yep... in ANY language the FPB is duplicated.
See http://dev.demo2.peacegeeks.org/ I only added one FPB in one Language

**Comment by MagdiRizkallah** [comment]
verified
