### ISSUE TITLE
Calendar dates unreadable for more than 1 year

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#725]
![screen shot 2015-03-15 at 4 07 45 am](https://cloud.githubusercontent.com/assets/2263033/6655773/e6d119be-cac8-11e4-9afd-47bec24b6fa1.png)

**Comment by tnightingale** [comment]
I have rotated the x-axis labels by about 65 degrees. While the bars are going to continue to get thinner as time goes on, it prevents the labels from overlapping and improves the readability of the chart.

This work has been pushed to the develop branch (1b11c68e0754bdd2215e1c42a427adf30fa4ebe0).

**Comment by tnightingale** [comment]
This work is deployed and visible on http://dev.cepo.peacegeeks.org/mapping-conflict-violence-in-south-sudan

**Comment by MagdiRizkallah** [comment]
verified
