### ISSUE TITLE
Strings Translation Import does not work?

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#731]
http://dev.demo1.peacegeeks.org/admin/config/regional/translate/translate
I exported, translated, then imported the Taxonomy group.  but when I look at them, no translation is imported...
Taxonomy.pot file at https://drive.google.com/drive/#folders/0BxiT_qSNZafUZDM4ZmQ1MjItMWQzMC00M2Y2LTg0NjEtYzc2Y2ZhYjAwYzNh/0B3VbDQ0s1eNLflh2N3V6OUdSNm1XU3d0SHlqU3M5YXVMYTh5NjY3R3F2d2xRVS1lNG90R0U/0BxiT_qSNZafUZEtjSWdYTnRFclU/0B8Xf2vogOufqfmpwa2lRRlhwUURrblRacHRabURKZEpmRnlTVUkxUUVBYVlVdXlya01HaVE

**Comment by bensinjin** [comment]
@MagdiRizkallah Just a few notes here, you should be uploading a po file - you can see examples of po files at https://localize.drupal.org. I have noticed that taxonomy terms are finicky and have actually only had success translating taxonomy terms via the ui.

**Comment by MagdiRizkallah** [comment]
Verified
