### ISSUE TITLE
Allow Amani Admin to Translate Donate Button title & link

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#736]
http://dev.demo1.peacegeeks.org/ar/admin/structure/menu/item/980

**Comment by bensinjin** [comment]
This should be working now - I'm not sure why it wasn't in the first place

**Comment by MagdiRizkallah** [comment]
@bensinjin Not fully working...  Since the Donate button is actually a menu link (I always wondered why it was different the Newsletter button), I added another link with the AR URL (node 71 vs node 8 for EN).  Now both buttons appear in Arabic since I could not change the Language of the original Donate button to English only.

**Comment by bensinjin** [comment]
@MagdiRizkallah seems to be a bit of a quirk with the translation stuff - what I ended up doing was just deleting the link and remaking in english it should be working now I don't think this will happen often it's just probably a side affect of bringing in translation after the content creation step. I don't know who created the Newsleter/Donate stuff and why one is a menu and the other is just static content but that seems to be the decision they made and thats just sort of how it all came to fruition.

**Comment by MagdiRizkallah** [comment]
Verified...
