### ISSUE TITLE
Allow Amani Admin to Translate Newsletter Button title & link

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#737]
http://dev.demo1.peacegeeks.org/ar/admin/configure-amani/newsletter-button

**Comment by bensinjin** [comment]
@MagdiRizkallah (once this is deployed) to translate the newsletter button goto 
<your-site>/admin/configure-amani/newsletter-button you'll see an option to switch between arabic/english at the top.

**Comment by MagdiRizkallah** [comment]
@bensinjin this is the same link as in the Amani Admin menu and no language option is there.

**Comment by bensinjin** [comment]
@MagdiRizkallah my mistake it should be there now, i had local settings not pushed

**Comment by MagdiRizkallah** [comment]
Verified...
