### ISSUE TITLE
Allow Amani Admin to Translate Site Info

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#738]
http://dev.demo1.peacegeeks.org/admin/configure-amani/site-info

**Comment by bensinjin** [comment]
@MagdiRizkallah (once this is deployed) to translate the newsletter button goto 
admin/config/system/site-information you'll see an option to switch between arabic/english at the top.

**Comment by MagdiRizkallah** [comment]
Should this link be added to the Amani Admin menu (e.g. a second button under the Site Info block)
Got there the first time and translated the Tagline.  But when I tried http://dev.demo1.peacegeeks.org/admin/config/system/site-information a second time, I got an 'Access denied' error???
Also, how do we translate the Address, Phone, & Hours of operation fields?

**Comment by bensinjin** [comment]
@MagdiRizkallah the rest of the things need to be translated via the string translation interface .. i'll look into a good solution for making this interface accessible

**Comment by MagdiRizkallah** [comment]
@bensinjin I don't think the string translation interface can handle field 'content'.  Am I right to assume it only handles field 'labels'?

**Comment by bensinjin** [comment]
@MagdiRizkallah the times they are a changing, go search for those fields.

**Comment by MagdiRizkallah** [comment]
verified...  It is certainly NOT intuitive...  Let us know when you get a better solution :)
