### ISSUE TITLE
Junk on any list view

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#739]
http://dev.demo1.peacegeeks.org/ar/resources

**Comment by bensinjin** [comment]
@MagdiRizkallah Junk?

**Comment by MagdiRizkallah** [comment]
![image](https://cloud.githubusercontent.com/assets/5035201/7026906/831eeffe-dd01-11e4-9642-459052fd7b19.png)

**Comment by abedkhooli** [comment]
Hi Magdi,

I don't have access to that site (demo1) but may be someone was just
pasting text there. Here's a copy of the page from the site we are
experimenting with:
http://dev.aidwatch.peacegeeks.org/ar/resources (en version has more).

Abed.

On Tue, Apr 7, 2015 at 6:38 PM, MagdiRizkallah <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/5035201/7026906/831eeffe-dd01-11e4-9642-459052fd7b19.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeks/amani/issues/739#issuecomment-90612889>.
>



-- 
Abed Khooli
Business Intelligence, Web Applications and Data Science Specialist
http://www.linkedin.com/in/akhooli

**Comment by bensinjin** [comment]
This looks good now? please consider closing if so @MagdiRizkallah

**Comment by MagdiRizkallah** [comment]
Does not look good on demo1 and we need to find out why.

The shown text is not on any field of the resource details: http://dev.demo1.peacegeeks.org/ar/node/69/edit
Only on the list of resources: http://dev.demo1.peacegeeks.org/ar/resources

**Comment by bensinjin** [comment]
Sorry @MagdiRizkallah  I was obviously missing what you meant, some really odd behaviour to be honest so I was playing with the view and removed the () from the more link and that seems to have fixed it .. beats me and it's kinda hard to debug what exactly is being rendered as it's in arabic .. anyways take a look on demo1.

**Comment by MagdiRizkallah** [comment]
Thanks Ben...  Which brings up a question in my mind.  Would replacing 'more' with some indicating icon be better in the long run (e.g. '...' or similar)

**Comment by abedkhooli** [comment]
This is actually in all view listings on demo1 (ex.
http://dev.demo1.peacegeeks.org/ar/news-and-events and
http://dev.demo1.peacegeeks.org/ar/programs) with same Arabic text. Looks
like the text is either in some code file or in the db (behavior not
present at dev.aidwatch).

On Thu, Apr 9, 2015 at 12:48 AM, Ben St John <notifications@github.com>
wrote:

> Sorry @MagdiRizkallah <https://github.com/MagdiRizkallah> I was obviously
> missing what you meant, some really odd behaviour to be honest so I was
> playing with the view and removed the () from the more link and that seems
> to have fixed it .. beats me and it's kinda hard to debug what exactly is
> being rendered as it's in arabic .. anyways take a look on demo1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeks/amani/issues/739#issuecomment-91045760>.
>



-- 
Abed Khooli
Business Intelligence, Web Applications and Data Science Specialist
http://www.linkedin.com/in/akhooli

**Comment by MagdiRizkallah** [comment]
I am reopening the issue and changing the title accordingly.  Also, will create another issue about translating the (more) string...

**Comment by MagdiRizkallah** [comment]
@abedkhooli Actually Abed you do have admin access to demo1 since it is a copy of an earlier AWP site.  Please let me know if you do have access to it.

**Comment by abedkhooli** [comment]
Yes, but I never edit there. I am only doing work at
http://dev.aidwatch.peacegeeks.org/

On Thu, Apr 9, 2015 at 6:18 PM, MagdiRizkallah <notifications@github.com>
wrote:

> @abedkhooli <https://github.com/abedkhooli> Actually Abed you do have
> admin access to demo1 since it is a copy of an earlier AWP site. Please let
> me know if you do have access to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeks/amani/issues/739#issuecomment-91261900>.
>



-- 
Abed Khooli
Business Intelligence, Web Applications and Data Science Specialist
http://www.linkedin.com/in/akhooli
