### ISSUE TITLE
Resource details view not localized

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#740]
http://dev.demo1.peacegeeks.org/ar/resource/%D9%85%D9%88%D8%B1%D8%AF-2

**Comment by bensinjin** [comment]
This should be addressed and up on dev shortly

**Comment by bensinjin** [comment]
The necessary strings for translating this page should now appear in the string translate interface

**Comment by MagdiRizkallah** [comment]
Verified. The field labels appear under the Fields text group.
