### ISSUE TITLE
Allow 'hiding' Date & Time of Map Report

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#759]
Currently both Date & Time fields are mandatory.  Could we remove the mandate?
If no entry, do not display the DATE OF REPORT section.
If only Date is entered display it only.
If only Time is entered, ignore it, do not display the DATE OF REPORT section.
Requested by GNWP

**Comment by bensinjin** [comment]
deployed to dev.

**Comment by bensinjin** [comment]
On second look this may not be immediately possible - the timeline requires these fields to be present and currently causes the map to break when it does not exist.

**Comment by MagdiRizkallah** [comment]
Verified
