### ISSUE TITLE
Map record not geolocating or saving for Amani Admins

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#760]
CEPO Amani Admins cannot create Map Records. 
- records not geolocating properly
- address fields not changing based on selected country as per normal
- user cannot save record

**Comment by MagdiRizkallah** [comment]
This is repeatable on Dev Amani...  Amani Admins cannot Add or Edit Map records...

**Comment by MagdiRizkallah** [comment]
verified
