### ISSUE TITLE
Map filters still show after disabling them

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeks/amani#762]
Both date line and filter 1 & 2 blocks do not disappear when disabled.
See gnwp.org/gnwp-members

**Comment by bensinjin** [comment]
deployed to dev.

**Comment by MagdiRizkallah** [comment]
Tx @bensinjin ...  Works fine for filter1 & 2, but can't get the timeline filter back???

**Comment by MagdiRizkallah** [comment]
Verifed
