### ISSUE TITLE
Complete GeekTheme Header

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#771]

**Comment by PeaceGeeks** [comment]
Refer to annotated designs document, items 1-6.  https://docs.google.com/spreadsheets/d/1O37HNPF7ddqWmCmvmIGIOlDW0AhKWZWQ0DNnDXUqik4/edit?usp=sharing

Production files to be found here. https://docs.google.com/spreadsheets/d/1O37HNPF7ddqWmCmvmIGIOlDW0AhKWZWQ0DNnDXUqik4/edit?usp=sharing

**Comment by nbosco** [comment]
Static content complete for theme header.
