### ISSUE TITLE
Complete Geek Theme Footer

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#772]
Refer to annotated designs document, items 18-21. https://docs.google.com/spreadsheets/d/1O37HNPF7ddqWmCmvmIGIOlDW0AhKWZWQ0DNnDXUqik4/edit?usp=sharing

Production files to be found here. 
https://drive.google.com/folderview?id=0B86cdZmwyts0fngtaFpGR1E0U1A2T0lQa011OEpGMGl3ZDAxX01abUhwUVQ1LWNITk5COFk&usp=sharing

**Comment by Rahims74** [comment]
Backend development complete ready for themeing
