### ISSUE TITLE
Rename 'MANAGE META MENU' 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#800]
Rename 'MANAGE META MENU' to 'Secondary Menu'

**Comment by nbosco** [comment]
Is this under the meta tag?

**Comment by MagdiRizkallah** [comment]
I think Renee meant rename to 'Manage Secondary Menu'

**Comment by PeaceGeeks** [comment]
correct.

**Comment by MagdiRizkallah** [comment]
verified
