### ISSUE TITLE
Rename 'Manage Donate Button'

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#801]
Rename 'Manage Donate Button' to ''Manage Floating Button'

**Comment by jayappnovation** [comment]
Do i have to change the label of the button "Configure donate button" as well?

**Comment by PeaceGeeks** [comment]
No that's ok - we can default it to 'Donate''  because we should have something there and that's how most people use it - but perhaps change the help text to read 

This action allows users to enable, disable, edit or delete your \'Donate\' button

**Comment by MagdiRizkallah** [comment]
I think ALL 'Donate' should be changed to 'Floating' otherwise it is confusing.

In the description you could add example Use as 'Donate' (explaining the link should go to a page where viewers can actually Donate $$$)

**Comment by PeaceGeeks** [comment]
Magdi, I defer to your judgment on this. Can you specify everything that should be changed then?

**Comment by nbosco** [comment]
I've updated this, and the dev site, please see: http://dev.amani-zen-theme.peacegeeks.org/admin/configure-amani

Let me know if its what you visioned.

**Comment by MagdiRizkallah** [comment]
looks good @nbosco.  I would remove the 'Contact us' reference since it is part of the main menu.

**Comment by nbosco** [comment]
Done

**Comment by MagdiRizkallah** [comment]
verified
