### ISSUE TITLE
Create Amani Zen Mobile design for Home page

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeks/amani#825]
Desktop files are here:
https://drive.google.com/open?id=0B3VbDQ0s1eNLfjU3b1pNdVB4Ty1DdEVtN1lOVTZfLUcwY3dabHhtYW9peXFfWkRfMjVGWUE

**Comment by limage** [comment]
https://drive.google.com/a/appnovation.com/folderview?id=0B3VbDQ0s1eNLfmtjQTB0UjBIMC1UbVBpdEQzZF9ZTldWZVlHTTRsSXRUak0yRWxCcDMtTmM&usp=sharing_eid
